apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: commerce
  labels:
    app: catalog
    branch: main
    version: 1.0.0
    author: hughbrien
    owner: hughbrien
    cluster: hpbx-mac-cluster
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
        branch: main
        version: 1.0.0
    spec:
      containers:
      - name: catalog
        image: docker.io/hughbrien/frontend:2.1.15
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        resources:
          limits:
            cpu: 750m
            ephemeral-storage: 2Gi
            memory: 1Gi
          requests:
            cpu: 245m
            # Reduce by 5 from 250 recommended
            ephemeral-storage: 1Gi
            memory: 234Mi
            # recude by 22 from 256 recommended
